// Ask the user for total amount of their car purchase
// Ask the user for the loan APR
// Ask the user for the duration of the loan (in months)

const READLINE = require('readline-sync');

// Add an arrow prompt to all text generated by the program
function prompt(message) {
  console.log(`=> ${message}`);
}

// Ensure that only numbers are entered
function isValidNumber(num) {
  return num.trimStart() === '' || Number.isNaN(Number(num)) || num <= 0;
}

// Ensure that only numbers and one decimal point are entered
function isDecimalNumber(num) {
  const REGEX = /^[0-9]+([.][0-9]+)?$/;
  return !REGEX.test(num) || num < 0;
}

// Ensure that only 'y' or 'n' is entered
function recalculatePayment(str) {
  return str.toLowerCase() !== 'y' && str.toLocaleLowerCase() !== 'n';
}

while (true) {
  
  console.clear();
  prompt("Welcome to Al's Auto Loans!");

  prompt("What's the total loan amount you require for your car purchase?");
  let loanAmount = READLINE.question();

  while (isValidNumber(loanAmount)) {
    prompt('Please enter an amount greater than zero.');
    loanAmount = READLINE.question();
  }

  console.clear();
  prompt("What's the annual percentage rate (APR) of your auto loan (e.g., enter 6.25% as '6.25')?");
  let loanAPR = READLINE.question();

  while (isDecimalNumber(loanAPR)) {
    prompt("Please enter the APR as positive numbers and one decimal point only.");
    loanAPR = READLINE.question();
  }

  console.clear();
  prompt("What is the duration of your loan in years (e.g., 5)?");
  let loanDurationYears = READLINE.question();

  while (isValidNumber(loanDurationYears)) {
    prompt('Please enter a number greater than zero.');
    loanDurationYears = READLINE.question();
  }

  // Convert APR to monthly interest rate if APR is greater than 0
  if (loanAPR > 0) {
    let monthlyInterestRate = (loanAPR / 100) / 12;

    // Convert loan duration from years to months
    let loanDurationMonths = loanDurationYears * 12;

    let monthlyPayment = loanAmount * (monthlyInterestRate /
      (1 - Math.pow((1 + monthlyInterestRate), (-loanDurationMonths))));
    let roundedMonthlyPayment = monthlyPayment.toFixed(2);
    let formattedMonthlyPayment = roundedMonthlyPayment.toLocaleString();
    
    console.clear();
    prompt(`Your monthly loan payment is $${formattedMonthlyPayment}.`);

  } else { // Omit APR from monthly payment calculation if interest is zero
    let monthlyPayment = loanAmount / (loanDurationYears * 12);
    let roundedMonthlyPayment = monthlyPayment.toFixed(2);
    let formattedMonthlyPayment = roundedMonthlyPayment.toLocaleString();

    prompt(`Your interest-free monthly loan payment is $${formattedMonthlyPayment}.`);
  }

  // Ask the user if they wish to recalculate the monthly payment
  prompt('Would you like to recalculate the monthly payment? (y/n)');
  let answerYesNo = READLINE.question();

  while (recalculatePayment(answerYesNo)) {
    prompt('Please enter y or n.');
    answerYesNo = READLINE.question();
  }

  if (answerYesNo.toLowerCase() === 'n') break;

}

// Tests cases:
// Loan amount: 10000, APR: 6.25, Duration in years: 5 ==> $194.49
// Loan amount: 10000, APR: 0, Duration in years: 4 ==> $208.33
