// Objectives for Rock, Paper, Scissors:
// Ask the user to make a choice (Rock, Paper, Scissors, Spock, or Lizard)
// Ask the computer to make a choice
// Calculate whether user or computer wins
// Display the winner
// Track scores fo user and computer and increment by one for each win
// Once score for either reaches 3, display the grand champion of the game
// Ask the user if they want to play again

const READLINE = require('readline-sync');
const VALID_CHOICES = {
  r: 'rock',
  p: 'paper',
  sc: 'scissors',
  sp: 'spock',
  l: 'lizard',
};

let userScore = 0;
let computerScore = 0;

// let shortcutKey;
// let computerChoice;
// let choice;

// Add an arrow prompt to all text generated by the program
function prompt(msg) {
  console.log(`=> ${msg}`);
}

function getValidateUserChoice() {
  prompt("Enter the shortcut key of your choice: rock (r), paper (p), scissors (sc), spock (sp), lizard (l)");
  let shortcutKey = READLINE.question();

  // Require the user to enter only the shortcut key
  if (!VALID_CHOICES.hasOwnProperty(shortcutKey)) {
    prompt("Enter only the shortcut key for your choice. For example, for 'rock', input 'r'.");
    shortcutKey = READLINE.question();
  } else {
    const choice = VALID_CHOICES[shortcutKey];
    console.log(`You chose ${choice}`);
    return choice;
  }
}

function calculateComputerChoice() {
  const VALID_CHOICES_ARRAY = Object.values(VALID_CHOICES);
  let randomIndex = Math.floor(Math.random() * VALID_CHOICES_ARRAY.length);
  let computerChoice = VALID_CHOICES_ARRAY[randomIndex];
  console.log(`Computer chose ${computerChoice}`);
  return computerChoice;
}

function calculateWinner(choice, computerChoice) {
  console.log(`choice: ${choice}, computerChoice: ${computerChoice}`);
  if ((choice === 'rock' && computerChoice === 'scissors') ||
      (choice === 'scissors' && computerChoice === 'paper') ||
      (choice === 'paper' && computerChoice === 'rock') ||
      (choice === 'rock' && computerChoice === 'lizard') ||
      (choice === 'lizard' && computerChoice === 'spock') ||
      (choice === 'spock' && computerChoice === 'scissors') ||
      (choice === 'scissors' && computerChoice === 'lizard') ||
      (choice === 'lizard' && computerChoice === 'paper') ||
      (choice === 'paper' && computerChoice === 'spock') ||
      (choice === 'spock' && computerChoice === 'rock')) {
    prompt("You won!");
    userScore += 1;
  } else if (choice === computerChoice) {
    prompt("It's a tie!");
    return "tie";
  } else {
    prompt("Computer wins!");
    computerScore += 1;
  }
}

// Welcome the user and introduce the rules of the game
console.clear();
prompt("Welcome to the Rock, Paper, Scissors, Spock, Lizard game!");
prompt("This game is similar to the classic Rock, Paper, Scissors game, but with an added twist: Spock and Lizard.");
prompt("In this version of the game, Rock beats Lizard, Lizard beats Spock, Spock beats Scissors,");
prompt("Scissors beats Lizard, Lizard beats Paper, Paper beats Spock, and Spock beats Rock.");

prompt("Got it? :) Press Enter to continue.");
READLINE.question("");

while (userScore < 3 && computerScore < 3) {
  const choice = getValidateUserChoice();
  const computerChoice = calculateComputerChoice();
  calculateWinner(choice, computerChoice);

  console.log(`User score: ${userScore}, Computer score: ${computerScore}`);
}

if (userScore === 3) {
  console.log("You are the grand champion!");
} else {
  console.log("Computer is the grand champion!");
}
